# Custom gitleaks configuration file for TravelPerk.
# Title for the gitleaks configuration file.
title = "Gitleaks x TravelPerk"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

# This is a global allowlist which has a higher order of precedence than rule-specific allowlists.
# If a commit listed in the `commits` field below is encountered then that commit will be skipped and no
# secrets will be detected for said commit. The same logic applies for regexes and paths.
[allowlist]
description = "global allow list"
paths = [
  # Tests
  '''\/test\/''',
  '''\/tests\/''',
  '''\/Test\/''',
  '''\/Tests\/''',
  '''\/UITests\/''',
  '''\/fixtures\/''',
  '''\/.test\/''',
  '''\/.tests\/''',
  # Directories
  '''.github\/''',
  '''.security_pipeline\/''',
  '''cypres\/''',
  '''lint\/''',
  '''pre-commit-hooks\/''',
  '''static\/''',
  '''locale\/''',
  # Files
  '''.coveragerc''',
  '''.dockerignore''',
  '''.gitignore''',
  '''.gitmodules''',
  '''NOTICE''',
  '''.nvmrc''',
  '''.pre-commit-config.yaml''',
  '''.prettierrc.js''',
  '''.sonarcloud.properties''',
  '''CODEOWNERS''',
  '''CONTRIBUTORS.txt''',
  '''cypress.json''',
  '''known_mypy_errors.json''',
  '''LICENSE.txt''',
  '''mypy.ini''',
  '''.semgrepignore''',
  '''.trivyignore.yaml''',
  # Extensions
  '''.*\.(jpg|png|jpeg|gif|ico|css|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|dll|pdb|exe|woff|woff2|eot|ttf|otf)$''',]
